<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Storm.Core\Storm.Core.csproj" />
    <ProjectReference Include="..\Storm.Dso\Storm.Dso.csproj" />
    <ProjectReference Include="..\Storm.Imtr\Storm.Imtr.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
